### ISSUE TITLE
Where can i find the macro?

### ISSUE THREAD

**Issue by einssechseins** [cdrpro-macros/recent-files#1]
Hi,

i did the install, but don't know where i can find the Icon...?

**Comment by SanichKotikov** [comment]
Hi,

1. Run & complete the Installer
2. Start CorelDRAW
3. Click OK in the pop-up question (if you don’t see it, open Macro Manager)

After these actions the macro can be open from Standard Bar (green save icon at the end).

**Comment by einssechseins** [comment]
Found! The icon was hidden. After resizing the bar it is there. Many thanks.

Sanich <notifications@github.com> schrieb am Mo., 15. Juli 2019, 19:14:

**Comment by einssechseins** [comment]
Hi, 
i installed now in Corel Draw 2019. And again i cannot find it. What else can i do?

**Comment by SanichKotikov** [comment]
Should work with the same steps. If it doesn't try to reset workspace (note it will reset all your UI customisations).
