### ISSUE TITLE
Has anybody managed to install it on Corel Draw 2020?

### ISSUE THREAD

**Issue by einssechseins** [cdrpro-macros/recent-files#3]

**Comment by SanichKotikov** [comment]
You have to update `make.nsi` to make the installer for 2020. You need to add `22` version in all blocks, like for 21 https://github.com/cdrpro-macros/recent-files/blob/master/make.nsi#L34

**Comment by einssechseins** [comment]
Ok, thanks. Will try.

Sanich <notifications@github.com> schrieb am Fr., 8. Jan. 2021, 06:11:
